<div class="col-md-6">
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('acl-home/default', ['controller' => 'user', 'action' => 'edit']));
	$form->prepare();
	?>
	<div class="panel panel-flat">
		<div class="panel-heading">
			<h5 class="panel-title">Cadastrar Usuário</h5>
		</div>
		<div class="panel-body">
			<?php echo $this->form()->openTag($form); ?>
			<?php echo $this->formHidden($form->get('id')); ?>
			<?php echo $this->formHidden($form->get('security')); ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('name')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('email')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('password')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('confirmPassword')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('role')); ?>
			</div>
			<?php echo $this->formRow($form->get('submit')); ?>
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>
