<div class="tab-content panel-body">
	<div class="tab-pane fade in active" id="basic-tab1">
		<?php
		if ($this->error) {
			?>
			<p>Usuário ou Senha Inválidos.</p>
			<?php
		}
		$form = $this->form;
		$form->setAttribute('action', $this->url('sistema-auth'));
		$form->prepare();
		echo $this->form()->openTag($form);
		?>
		<div class="text-center">
			<div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
			<h5 class="content-group">Entre para sua conta
				<small class="display-block">Suas credenciais</small>
			</h5>
		</div>

		<div class="form-group has-feedback has-feedback-left">
			<?php echo $this->formRow($form->get('email')); ?>
			<div class="form-control-feedback">
				<i class="icon-user text-muted"></i>
			</div>
		</div>

		<div class="form-group has-feedback has-feedback-left">
			<?php echo $this->formRow($form->get('password')); ?>
			<div class="form-control-feedback">
				<i class="icon-lock2 text-muted"></i>
			</div>
		</div>

		<div class="form-group login-options">
			<div class="row">
				<div class="col-sm-6">
					<label class="checkbox-inline">
						<input type="checkbox" class="styled" checked="checked">
						Remember
					</label>
				</div>

				<div class="col-sm-6 text-right">
					<a href="login_password_recover.html">Forgot password?</a>
				</div>
			</div>
		</div>

		<div class="form-group">
			<?php echo $this->formRow($form->get('submit')); ?>
		</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
