<?php echo $this->doctype(); ?>

<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('ZF2 Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
	                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
	                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
	                ->prependStylesheet($this->basePath('css/style.css'))
	                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
	                ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
	                ->prependFile($this->basePath('js/bootstrap.min.js'))
	                ->prependFile($this->basePath('js/jquery.min.js'))
	                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
	                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',]); ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;Skeleton Application</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="<?php echo $this->url('home') ?>">Home</a></li>
				<li><a href="<?php echo $this->url('sistema-home') ?>">Administração</a></li>
				<li><a href="<?php echo $this->url('acl-home') ?>">Configurações</a></li>
				<?php if ($this->UserIdentity('Sistema')) {
					?>
					<li><a href="<?php echo $this->url('sistema-logout') ?>">Logout</a></li>
					<?php
				} ?>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
<div class="container">
	<?php // Sistema de avisos ?>
	<?php echo $this->flashMessenger()->setMessageOpenFormat('<div%s><a data-dismiss="alert" class="close">×</a>')
	                ->setMessageCloseString('</div>')
	                ->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS, ['alert', 'alert-success']); ?>
	<?php echo $this->flashMessenger()->setMessageOpenFormat('<div%s><a data-dismiss="alert" class="close">×</a>')
	                ->setMessageCloseString('</div>')
	                ->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR, ['alert', 'alert-danger']); ?>
	<?php echo $this->flashMessenger()->setMessageOpenFormat('<div%s><a data-dismiss="alert" class="close">×</a>')
	                ->setMessageCloseString('</div>')
	                ->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO, ['alert', 'alert-warning']); ?>
	<?php echo $this->flashMessenger()->setMessageOpenFormat('<div%s><a data-dismiss="alert" class="close">×</a>')
	                ->setMessageCloseString('</div>')
	                ->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING, ['alert']); ?>
	<?php echo $this->content; ?>
	<hr>
	<footer>
		<p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo 'All rights reserved.' ?></p>
	</footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
